package com.nukkitx.protocol.bedrock.v113;

import com.nukkitx.protocol.bedrock.BedrockPacketCodec;
import com.nukkitx.protocol.bedrock.packet.*;
import com.nukkitx.protocol.bedrock.v113.serializer.*;
import lombok.experimental.UtilityClass;

@UtilityClass
public class Bedrock_v113 {
    public static final BedrockPacketCodec V113_CODEC = BedrockPacketCodec.builder()
            .raknetProtocolVersion(8)
            .protocolVersion(113)
            .minecraftVersion("1.1.0")
            .helper(BedrockPacketHelper_v113.INSTANCE)
            .registerPacket(LoginPacket.class, LoginSerializer_v113.INSTANCE, 1)
            .registerPacket(PlayStatusPacket.class, PlayStatusSerializer_v113.INSTANCE, 2)
            .registerPacket(ServerToClientHandshakePacket.class, ServerToClientHandshakeSerializer_v113.INSTANCE, 3)
            .registerPacket(ClientToServerHandshakePacket.class, ClientToServerHandshakeSerializer_v113.INSTANCE, 4)
            .registerPacket(DisconnectPacket.class, DisconnectSerializer_v113.INSTANCE, 5)
            .registerPacket(ResourcePacksInfoPacket.class, ResourcePacksInfoSerializer_v113.INSTANCE, 6)
            .registerPacket(ResourcePackStackPacket.class, ResourcePackStackSerializer_v113.INSTANCE, 7)
            .registerPacket(ResourcePackClientResponsePacket.class, ResourcePackClientResponseSerializer_v113.INSTANCE, 8)
            .registerPacket(TextPacket.class, TextSerializer_v113.INSTANCE, 9)
            .registerPacket(SetTimePacket.class, SetTimeSerializer_v113.INSTANCE, 10)
            .registerPacket(StartGamePacket.class, StartGameSerializer_v113.INSTANCE, 11)
            .registerPacket(AddPlayerPacket.class, AddPlayerSerializer_v113.INSTANCE, 12)
            .registerPacket(AddEntityPacket.class, AddEntitySerializer_v113.INSTANCE, 13)
            .registerPacket(RemoveEntityPacket.class, RemoveEntitySerializer_v113.INSTANCE, 14)
            .registerPacket(AddItemEntityPacket.class, AddItemEntitySerializer_v113.INSTANCE, 15)
            .registerPacket(AddHangingEntityPacket.class, AddHangingEntitySerializer_v113.INSTANCE, 16)
            .registerPacket(TakeItemEntityPacket.class, TakeItemEntitySerializer_v113.INSTANCE, 17)
            .registerPacket(MoveEntityPacket.class, MoveEntitySerializer_v113.INSTANCE, 18)
            .registerPacket(MovePlayerPacket.class, MovePlayerSerializer_v113.INSTANCE, 19)
            .registerPacket(RiderJumpPacket.class, RiderJumpSerializer_v113.INSTANCE, 20)
            .registerPacket(RemoveBlockPacket.class, RemoveBlockSerializer_v113.INSTANCE, 21)
            .registerPacket(UpdateBlockPacket.class, UpdateBlockSerializer_v113.INSTANCE, 22)
            .registerPacket(AddPaintingPacket.class, AddPaintingSerializer_v113.INSTANCE, 23)
            .registerPacket(ExplodePacket.class, ExplodeSerializer_v113.INSTANCE, 24)
            .registerPacket(LevelSoundEventPacket.class, LevelSoundEventSerializer_v113.INSTANCE, 25)
            .registerPacket(LevelEventPacket.class, LevelEventSerializer_v113.INSTANCE, 26)
            .registerPacket(BlockEventPacket.class, BlockEventSerializer_v113.INSTANCE, 27)
            .registerPacket(EntityEventPacket.class, EntityEventSerializer_v113.INSTANCE, 28)
            .registerPacket(MobEffectPacket.class, MobEffectSerializer_v113.INSTANCE, 29)
            .registerPacket(UpdateAttributesPacket.class, UpdateAttributesSerializer_v113.INSTANCE, 30)
            .registerPacket(MobEquipmentPacket.class, MobEquipmentSerializer_v113.INSTANCE, 31)
            .registerPacket(MobArmorEquipmentPacket.class, MobArmorEquipmentSerializer_v113.INSTANCE, 32)
            .registerPacket(InteractPacket.class, InteractSerializer_v113.INSTANCE, 33)
            .registerPacket(BlockPickRequestPacket.class, BlockPickRequestSerializer_v113.INSTANCE, 34)
            .registerPacket(UseItemPacket.class, UseItemSerializer_v113.INSTANCE, 35)
            .registerPacket(PlayerActionPacket.class, PlayerActionSerializer_v113.INSTANCE, 36)
            .registerPacket(EntityFallPacket.class, EntityFallSerializer_v113.INSTANCE, 37)
            .registerPacket(HurtArmorPacket.class, HurtArmorSerializer_v113.INSTANCE, 38)
            .registerPacket(SetEntityDataPacket.class, SetEntityDataSerializer_v113.INSTANCE, 39)
            .registerPacket(SetEntityMotionPacket.class, SetEntityMotionSerializer_v113.INSTANCE, 40)
            .registerPacket(SetEntityLinkPacket.class, SetEntityLinkSerializer_v113.INSTANCE, 41)
            .registerPacket(SetHealthPacket.class, SetHealthSerializer_v113.INSTANCE, 42)
            .registerPacket(SetSpawnPositionPacket.class, SetSpawnPositionSerializer_v113.INSTANCE, 43)
            .registerPacket(AnimatePacket.class, AnimateSerializer_v113.INSTANCE, 44)
            .registerPacket(RespawnPacket.class, RespawnSerializer_v113.INSTANCE, 45)
            .registerPacket(DropItemPacket.class, DropItemSerializer_v113.INSTANCE, 46)
            .registerPacket(InventoryActionPacket.class, InventoryActionSerializer_v113.INSTANCE, 47)
            .registerPacket(ContainerOpenPacket.class, ContainerOpenSerializer_v113.INSTANCE, 48)
            .registerPacket(ContainerClosePacket.class, ContainerCloseSerializer_v113.INSTANCE, 49)
            .registerPacket(ContainerSetSlotPacket.class, ContainerSetSlotSerializer_v113.INSTANCE, 50)
            .registerPacket(ContainerSetDataPacket.class, ContainerSetDataSerializer_v113.INSTANCE, 51)
            .registerPacket(ContainerSetContentPacket.class, ContainerSetContentSerializer_v113.INSTANCE, 52)
            .registerPacket(CraftingDataPacket.class, CraftingDataSerializer_v113.INSTANCE, 53)
            .registerPacket(CraftingEventPacket.class, CraftingEventSerializer_v113.INSTANCE, 54)
            .registerPacket(AdventureSettingsPacket.class, AdventureSettingsSerializer_v113.INSTANCE, 55)
            .registerPacket(BlockEntityDataPacket.class, BlockEntityDataSerializer_v113.INSTANCE, 56)
            .registerPacket(PlayerInputPacket.class, PlayerInputSerializer_v113.INSTANCE, 57)
            .registerPacket(FullChunkDataPacket.class, FullChunkDataSerializer_v113.INSTANCE, 58)
            .registerPacket(SetCommandsEnabledPacket.class, SetCommandsEnabledSerializer_v113.INSTANCE, 59)
            .registerPacket(SetDifficultyPacket.class, SetDifficultySerializer_v113.INSTANCE, 60)
            .registerPacket(ChangeDimensionPacket.class, ChangeDimensionSerializer_v113.INSTANCE, 61)
            .registerPacket(SetPlayerGameTypePacket.class, SetPlayerGameTypeSerializer_v113.INSTANCE, 62)
            .registerPacket(PlayerListPacket.class, PlayerListSerializer_v113.INSTANCE, 63)
            .registerPacket(SimpleEventPacket.class, SimpleEventSerializer_v113.INSTANCE, 64)
            .registerPacket(EventPacket.class, EventSerializer_v113.INSTANCE, 65)
            .registerPacket(SpawnExperienceOrbPacket.class, SpawnExperienceOrbSerializer_v113.INSTANCE, 66)
            .registerPacket(ClientboundMapItemDataPacket.class, ClientboundMapItemDataSerializer_v113.INSTANCE, 67)
            .registerPacket(MapInfoRequestPacket.class, MapInfoRequestSerializer_v113.INSTANCE, 68)
            .registerPacket(RequestChunkRadiusPacket.class, RequestChunkRadiusSerializer_v113.INSTANCE, 69)
            .registerPacket(ChunkRadiusUpdatedPacket.class, ChunkRadiusUpdatedSerializer_v113.INSTANCE, 70)
            .registerPacket(ItemFrameDropItemPacket.class, ItemFrameDropItemSerializer_v113.INSTANCE, 71)
            .registerPacket(ReplaceItemInSlotPacket.class, ReplaceItemInSlotSerializer_v113.INSTANCE, 72)
            .registerPacket(GameRulesChangedPacket.class, GameRulesChangedSerializer_v113.INSTANCE, 73)
            .registerPacket(CameraPacket.class, CameraSerializer_v113.INSTANCE, 74)
            .registerPacket(AddItemPacket.class, AddItemSerializer_v113.INSTANCE, 75)
            .registerPacket(BossEventPacket.class, BossEventSerializer_v113.INSTANCE, 76)
            .registerPacket(ShowCreditsPacket.class, ShowCreditsSerializer_v113.INSTANCE, 77)
            .registerPacket(AvailableCommandsPacket.class, AvailableCommandsSerializer_v113.INSTANCE, 78)
            .registerPacket(CommandStepPacket.class, CommandStepSerializer_v113.INSTANCE, 79)
            .registerPacket(CommandBlockUpdatePacket.class, CommandBlockUpdateSerializer_v113.INSTANCE, 80)
            .registerPacket(UpdateTradePacket.class, UpdateTradeSerializer_v113.INSTANCE, 81)
            .registerPacket(UpdateEquipPacket.class, UpdateEquipSerializer_v113.INSTANCE, 82)
            .registerPacket(ResourcePackDataInfoPacket.class, ResourcePackDataInfoSerializer_v113.INSTANCE, 83)
            .registerPacket(ResourcePackChunkDataPacket.class, ResourcePackChunkDataSerializer_v113.INSTANCE, 84)
            .registerPacket(ResourcePackChunkRequestPacket.class, ResourcePackChunkRequestSerializer_v113.INSTANCE, 85)
            .registerPacket(TransferPacket.class, TransferSerializer_v113.INSTANCE, 86)
            .registerPacket(PlaySoundPacket.class, PlaySoundSerializer_v113.INSTANCE, 87)
            .registerPacket(StopSoundPacket.class, StopSoundSerializer_v113.INSTANCE, 88)
            .registerPacket(SetTitlePacket.class, SetTitleSerializer_v113.INSTANCE, 89)
            .registerPacket(AddBehaviorTreePacket.class, AddBehaviorTreeSerializer_v113.INSTANCE, 90)
            .registerPacket(StructureBlockUpdatePacket.class, StructureBlockUpdateSerializer_v113.INSTANCE, 91)
            .registerPacket(ShowStoreOfferPacket.class, ShowStoreOfferSerializer_v113.INSTANCE, 92)
            .registerPacket(PurchaseReceiptPacket.class, PurchaseReceiptSerializer_v113.INSTANCE, 93)
            .build();
}
